lms1/urls.py
from django.contrib import admin
from django.urls import path
from api import views
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/',views.Book_create,name='book'),
    path('',views.book_view,name='booklist'),
    path('<int:id>/',views.bookUpdate,name='update'),
    path('delete/<id>/',views.deleteBook,name='delete')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/models.py
from django.db import models

# Create your models here.

class Category1(models.Model):
    name=models.CharField(max_length=100)


    def __str__(self):
        return str(self.name)

class BookType1(models.Model):
    type=models.CharField(max_length=100)

    def __str__(self):
        return str(self.type)        


class Book1(models.Model):
    # bookid=models.CharField(max_length=10)
    btype = models.ForeignKey(BookType1,on_delete=models.CASCADE)
    category = models.ForeignKey(Category1,on_delete=models.CASCADE)
    bookname=models.CharField(max_length=50)
    description=models.CharField(max_length=500)
    pub_date=models.DateField()
    price=models.FloatField()
    cover_image = models.ImageField(null= True, blank=True,upload_to='uploads/images/')
#     TYPE = (
    #        ('Sports','Sports'),
#        ('Educational', 'Educational'),
#        ('Motivationa','Motivational')
#    )
#     type = models.CharField(
#        max_length=30,
#        choices=TYPE,
#        default='available',
#    )

    def __str__(self):
        return str(self.bookname)

api/forms.py
from django import forms
from .models import Book1,Category1,BookType1
 
 
class BookForm(forms.ModelForm):
    class Meta:
        model = Book1
        fields = ['bookname','category','btype','description','pub_date','price','cover_image']
        # widgets={
        #     'bookname': forms.TextInput(attrs={'class':'form-control'}),
        #     # 'category': forms.TextInput(attrs={'class':'form-control'}),
        #     # 'btype': forms.TextInput(attrs={'class':'form-control'}),
        #     'description': forms.TextInput(attrs={'class':'form-control'}),
        #     'pub_date': forms.DateField(attrs={'class':'form-control'}),
        #      'price': forms.FloatField(attrs={'class':'form-control'}),
        #     'cover_image': forms.ImageField(attrs={'class':'form-control'}),

        # }

api/views.py
from django.shortcuts import render,redirect
from .models import Book1
from .forms import BookForm
from django.contrib import messages
from django.shortcuts import (get_object_or_404,render,HttpResponseRedirect)
                              
def Book_create(request):
    context={}
    if request.method == "POST": 
        form = BookForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                messages.success(request, "Thank you! You have successfully  Added book")
                return redirect('/') 
            except:
                pass
        else:
            form=BookForm()           
            context['form']= form
    return render(request, "bookcreate.html", context)

def book_view(request):
    context ={}
    context["dataset"] = Book1.objects.all()
    return render(request, "booklist.html", context)  


# def booKEdit(request, id):
#     context ={}
#     context["data"] = Book1.objects.get(id = id)
#     return render(request, "bookedit.html", context)
 

# update view for Books
def bookUpdate(request, id):
    if request.method=='POST':
        obj = Book1.objects.get(id = id)
        form = BookForm(request.POST, instance = obj)
        if form.is_valid():
            form.save()
    else:
        obj = Book1.objects.get(id = id)
        form = BookForm(instance = obj)
    return render(request, "updatebook.html", {'form':form})      

def deleteBook(request, id):
    context ={}
    obj = get_object_or_404(Book1, id = id)
    if request.method =="POST":
        obj.delete()
        return HttpResponseRedirect("/")
 
    # return render(request, "deletebook.html", context)

api/templates/base.html
<!DOCTYPE html> 
{% load static %} 
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Library Management system</title>   
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>  
</head>  
<body>
<div class="container mt-5">
<h2 class = "text-center alert alert-danger"> CRUD ON LIBRARY MANAGEMENT</h2> 
{% block content %}  {% endblock content %}
</div>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/proper.js' %}"></script>

</body>
</html>

api/templates/bookcreate.html
{% extends 'base.html'%}
{% block content %}
<h4 class="alert alert-info">UPDATE BOOK DETAILS</h4> 
<form  action="" method="POST" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-success" value="Add">
</form>
{% endblock content  %}

api/templates/bookedit.html
{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
  <title>Edit Book</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
{% load static %}
<div class="container">           
  <table class="table table-hover border="1">
    <thead>
      <tr>
        <th>BookId</th>
        <th>BTYPE</th>
        <th>Category</th>
        <th>BOOK_NAME</th>
        <th>DESCRIPTION</th>
        <th>Pub_Date</th>
        <th>Price</th>
        <th>BOOKCOVER_IMAGE</th>
      </tr>
    </thead>
    <tbody>

    {% for data in dataset %}
    <tr>
 
    <td>{{ data.bookid }}</td>
    <td>{{ data.btype }}</td>
    <td>{{ data.category }}</td>
    <td>{{ data.bookname }}</td>
    <td>{{ data.description }}</td>
    <td> {{ data.pub_date }}<td
    <td>{{ data.price }}</td>
    <td>{{ data.cover_image }}</td>
    </tr>
    {% endfor %}
      
    </tbody>
  </table>
</div>

</body>
</html> {% endcomment %}

<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Update</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/bookupdate/{{data.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">BookId:</label>  
    <div class="col-sm-4">  
        <input type="text" name="bookid" id="id_bookid" required maxlength="20" value="{{ data.bookid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">BTYPE:</label>  
    <div class="col-sm-4">  
        <input type="text" name="btype" id="id_btype" required maxlength="100" value="{{ data.btype }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Category:</label>  
    <div class="col-sm-4">  
        <input type="text" name="category" id="id_category" required maxlength="254" value="{{ data.category }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">BOOK_NAME:</label>  
    <div class="col-sm-4">  
        <input type="text" name="bookname" id="id_bookname" required maxlength="15" value="{{ data.bookname }}" />  
    </div>  
  </div>

   <div class="form-group row">  
    <label class="col-sm-2 col-form-label">DESCRIPTION:</label>  
    <div class="col-sm-4">  
        <input type="text" name="description" id="id_description" required maxlength="15" value="{{ data.description }}" />  
    </div>  
  </div>  

   <div class="form-group row">  
    <label class="col-sm-2 col-form-label">PUB_DATE:</label>  
    <div class="col-sm-4">  
        <input type="text" name="pub_date" id="id_pub_date" required maxlength="15" value="{{ data.pub_date }}" />  
    </div>  
  </div>  

   <div class="form-group row">  
    <label class="col-sm-2 col-form-label">PRICE:</label>  
    <div class="col-sm-4">  
        <input type="text" name="price" id="id_price" required maxlength="15" value="{{ data.price }}" />  
    </div>  
  </div> 

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">IMAGE:</label>  
    <div class="col-sm-4">  
        <input type="text" name="cover_image" id="id_cover_image" required maxlength="15" value="{{ data.cover_image }}" />  
    </div>  
  </div>       
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

api/templates/booklist.html
{% extends 'base.html'%}
{% block content %}          
  <table class="table table-striped table-bordered table-sm>
    <thead class="thead-dark>
      <tr>
        <th>BOOK_ID</th>
        <th>BOOK_TYPE</th>
        <th>CATEGORIES</th>
        <th>BOOKNAME</th>
        <th>DESCRIPTION</th>
        <th>PUBLICATION_DATE</th>
        <th>PRICE</th>
        <th>BOOK_COVER_IMAGE</th>
        <th>ACTION</th>
      </tr>
    </thead>
    <tbody>
    {% for data in dataset %}
    <tr>
    <td>{{ data.id }}</td>
    <td>{{ data.btype }}</td>
    <td>{{ data.category }}</td>
    <td>{{ data.bookname }}</td>
    <td>{{ data.description }}</td>
    <td> {{ data.pub_date }}<td
    <td>{{ data.price }}</td>
    <td>{{ data.cover_image }}</td>
    <td><a href="{% url 'update' data.id %}" class="btn btn-warning sm ">Edit</a>

    <form action="{% url 'delete' data.id %}" method="post" class="d-inline">
    {% csrf_token %}
    <input type="submit"  class="btn btn-danger sm" value="delete">
    </form>
    </td> 
    </tr>
    {% endfor %}
    </tbody>
  </table>
<center><a href="/book" class="btn btn-primary">Add New Record</a></center>
{% endblock content %}

api/templates/deletebook.html
<div class="main">
    <form method="POST">
        {% csrf_token %}
        Are you want to delete this Book ?
        <input type="submit" value="Yes" />
        <a href="/">Cancel </a>
    </form>
</div>

api/templates/updatebook.html
{% extends 'base.html'%}
{% block content %}
<div class="row">
<div class="col-sm-8 offset-2">
<h4 class="alert alert-info">UPDATE BOOK DETAILS</h4>
<form method="POST" class="post-form" action="">  
        {% csrf_token %} 
        {{form.as_p}}
        <input type="submit" class="btn btn-success" value="update">
        <a href="{% url 'booklist' %}" class="btn btn-info">Back to Home</a>
        </form>
        </div>
        </div>
        {% endblock content %}



{% comment %} <!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Update</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>  
</head>  
<body>  
 
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">BookId:</label>  
    <div class="col-sm-4">  
        <input type="text" name="bookid" id="id_bookid" required maxlength="20" value="{{ data.bookid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">BTYPE:</label>  
    <div class="col-sm-4">  
        <input type="text" name="btype" id="id_btype" required maxlength="100" value="{{ data.btype }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Category:</label>  
    <div class="col-sm-4">  
        <input type="text" name="category" id="id_category" required maxlength="254" value="{{ data.category }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">BOOK_NAME:</label>  
    <div class="col-sm-4">  
        <input type="text" name="bookname" id="id_bookname" required maxlength="15" value="{{ data.bookname }}" />  
    </div>  
  </div>

   <div class="form-group row">  
    <label class="col-sm-2 col-form-label">DESCRIPTION:</label>  
    <div class="col-sm-4">  
        <input type="text" name="description" id="id_description" required maxlength="15" value="{{ data.description }}" />  
    </div>  
  </div>  

   <div class="form-group row">  
    <label class="col-sm-2 col-form-label">PUB_DATE:</label>  
    <div class="col-sm-4">  
        <input type="text" name="pub_date" id="id_pub_date" required maxlength="15" value="{{ data.pub_date }}" />  
    </div>  
  </div>  

   <div class="form-group row">  
    <label class="col-sm-2 col-form-label">PRICE:</label>  
    <div class="col-sm-4">  
        <input type="text" name="price" id="id_price" required maxlength="15" value="{{ data.price }}" />  
    </div>  
  </div> 

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">IMAGE:</label>  
    <div class="col-sm-4">  
        <input type="text" name="cover_image" id="id_cover_image" required maxlength="15" value="{{ data.cover_image }}" />  
    </div>  
  </div>       
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>   {% endcomment %}